[package]
name = "my_project"  
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "indicator_benchmark"
harness = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
ndarray = "0.16.1"
chrono = "0.4.39"


[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "my_project"
path = "src/main.rs"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[build]
rustflags = ["-C", "target-cpu=native"]
