[package]
name = "my_project"  
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
lazy_static = "1.4"

[[bench]]
name = "indicator_benchmark"
harness = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
lazy_static = "1.5.0"
ndarray = "0.16.1"


[lib]
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "my_project"
path = "src/main.rs"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[profile.bench]
inherits = "release"
lto = true
opt-level = 3
codegen-units = 1
debug = false
incremental = false

[build]
rustflags = ["-C", "target-cpu=native","-Z", "threads=16"]